baseURL = 'https://christiansassi.github.io/knowledge-graph-engineering-project'
languageCode = 'en-us'
title = 'Sports Facilities & Events in Trentino'
theme = 'PaperMod'
publishDir = "../../docs"
assetDir = "assets"